---

winrm_retry: 5
winrm_retry_delay: 10
force_basic_auth: yes
status_code: 200
return_content: yes

7zip_version: 'latest'
7zip_filename: '7z1900-x64.exe'
jfrog_base_url: 'https://artifactory.solutions.corelogic.com/artifactory'
jfrog_repo: 'edg_legacy_us-diabloplus-generic-release-3rdparty-local'

install_folder: "C:\\Installers"
winsxs_folder: "C:\\Installers\\WinSxS"
app_base_path: 'C:\\Program Files (x86)\\'
npp_version: "7.9.3"
