---

jfrog_version: 'latest'
project_name: 'DirectMatchDLL'
winrm_retry: 5
winrm_retry_delay: 10
force_basic_auth: yes
status_code: 200
return_content: yes

#folder directory to copy cmas projects
#dest_location: 'C:\\Apps\\CMAS\\DirectMatch_4.5.2'
dest_location: 'D:\Apps\_Deployment\DirectMatch'

# gac manager path to install the application dll to database Server
gac_base_path: 'C:\\Program Files (x86)\\'

jfrog_base_url: 'https://artifactory.solutions.corelogic.com/artifactory'
jfrog_repo: 'edg_legacy_us-diabloplus-generic-release-local'
